### ISSUE TITLE
BadTokenException

### ISSUE THREAD

**Issue by DXH100** [DSAppTeam/PanelSwitchHelper#175]
Process Name: 'com.yilahuo.driftbottle'
Thread Name: 'main'
Back traces starts.
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@dd9650e is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1279)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:410)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1730)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1489)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1455)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.show(FloatingToolbar.java:774)
	at com.android.internal.widget.FloatingToolbar.doShow(FloatingToolbar.java:324)
	at com.android.internal.widget.FloatingToolbar.show(FloatingToolbar.java:249)
	at com.android.internal.view.FloatingActionMode$FloatingToolbarVisibilityHelper.updateToolbarVisibility(FloatingActionMode.java:428)
	at com.android.internal.view.FloatingActionMode.repositionToolbar(FloatingActionMode.java:226)
	at com.android.internal.view.FloatingActionMode.updateViewLocationInWindow(FloatingActionMode.java:176)
	at com.android.internal.view.FloatingActionMode.invalidateContentRect(FloatingActionMode.java:154)
	at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:148)
	at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:2435)
	at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:2275)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1168)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:1123)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1087)
	at android.view.View.startActionMode(View.java:7716)
	at android.widget.Editor.startInsertionActionMode(Editor.java:2548)
	at android.widget.TextView.onTouchEvent(TextView.java:11470)
	at android.view.View.dispatchTouchEvent(View.java:14692)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at com.effective.android.panel.view.content.LinearContentContainer.dispatchTouchEvent(LinearContentContainer.java:87)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3201)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2866)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:691)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:942)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:643)
	at android.view.View.dispatchPointerEvent(View.java:14964)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6905)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6671)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6121)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6188)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6149)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6322)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6157)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6379)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6125)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6188)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6149)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6157)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6125)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9227)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9178)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9362)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:276)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8396)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
Back traces ends.

**Comment by HeroZ-Dodge** [comment]
是升级到 v1.5.0版本后，出现问题了吗
