### ISSUE TITLE
集成后吊起键盘报错空指针

### ISSUE THREAD

**Issue by wang521314** [DSAppTeam/PanelSwitchHelper#176]
Androidx版本：是

PanelSwitchHelper版本：v1.5.1

手机型号: 一加8t

手机系统版本： Android 11

问题描述：集成后吊起键盘或者点击表情按钮崩溃,报错信息显示空指针,但不清楚具体哪里导致的

Log提供：错误日志

java.lang.IllegalStateException: view must not be null
    at com.effective.android.panel.view.content.ContentContainerImpl.translationContainer(ContentContainerImpl.kt:433)
    at com.effective.android.panel.view.content.RelativeContentContainer.translationContainer(RelativeContentContainer.kt:71)
    at com.effective.android.panel.view.PanelSwitchLayout$keyboardChangedAnimation$callback$1.onProgress(PanelSwitchLayout.kt:369)
    at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:1022)
    at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:11463)
    at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7463)
    at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:106)
    at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:610)
    at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run(Unknown Source:2)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
    at android.view.Choreographer.doFrame(Choreographer.java:1046)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8030)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by HeroZ-Dodge** [comment]
> translationContainer

你是不是又调用 addContentScrollMeasurer 方法，然后返回的 viewId 不在你的布局文件中

**Comment by wang521314** [comment]
> 

好像是的多谢回复!
