### ISSUE TITLE
bug，崩溃

### ISSUE THREAD

**Issue by diandian8801** [DSAppTeam/PanelSwitchHelper#199]
测试机型为：红米 K40 Pro（安卓13），小米13（安卓14）机型。

报错：PanelSwitchLayout.kt  （597行）--->里面的`    private fun releaseKeyboardChangedListener() {
        if (keyboardAnimationFeature || supportKeyboardFeature()) {
            val rootView = windowInsetsRootView ?: window.decorView.rootView
            ViewCompat.setOnApplyWindowInsetsListener(rootView, null)
        } else {
            globalLayoutListener?.let {
                window.decorView.rootView.viewTreeObserver.removeOnGlobalLayoutListener(it)
            }
        }
        hasAttachLister = false
    }`

文件中的79行，定义了windows，private lateinit var window: Window

**在 PanelSwitchLayout 的 releaseKeyboardChangedListener 方法中,试图访问名为 window 的后期初始化属性,但这个属性其实并没有初始化,所以抛出了 kotlin.UninitializedPropertyAccessException。**

![微信截图_20230804185705](https://github.com/DSAppTeam/PanelSwitchHelper/assets/38841095/a8d5a06c-99ca-4b17-b60d-1cfe7f9c195f)

**Comment by diandian8801** [comment]
kotlin.UninitializedPropertyAccessException: lateinit property window has not been initialized
	at com.effective.android.panel.view.PanelSwitchLayout.releaseKeyboardChangedListener(PanelSwitchLayout.kt:597)
	at com.effective.android.panel.view.PanelSwitchLayout.recycle(PanelSwitchLayout.kt:165)
	at com.effective.android.panel.view.PanelSwitchLayout.onDetachedFromWindow(PanelSwitchLayout.kt:150)
	at android.view.View.dispatchDetachedFromWindow(View.java:21465)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3968)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3960)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5589)
	at android.view.ViewGroup.removeViewAt(ViewGroup.java:5536)
	at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:915)

**Comment by 15359947959** [comment]
收到了，辛苦啦

**Comment by HeroZ-Dodge** [comment]
v1.5.6已修复
