### ISSUE TITLE
Android 10 以及Android 10 以下，出现下面的崩溃，看日志

### ISSUE THREAD

**Issue by lianyagang** [DSAppTeam/PanelSwitchHelper#216]
1.  现象：崩溃
2. 场景：线上的场景，不知道用户怎么操作的
3. 系统版本：目前是大量Android10 以及以下的出现崩溃，Android10以上是没有出现过
4. 疑问：com.effective.android.panel.view.content.ContentContainerImpl.layoutContainer(ContentContainerImpl.kt:380) 这个摆放的时候，如果在低端机，或者低内存下，渲染不及时，不是会有问题吗？

 Fatal Exception: java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.xxxx.AutoHideXXxxPanelRecyclerView{cf58a2a VFED..... ......ID 0,0-720,1001 #7f0a0c38 app:id/recyclerView}, adapter:com.xxx.adapter.wrapper.HeaderAndFooterAdapterWrapper@65191a4, layout:com.xxxx..CatchLinearLayoutManager@1ff57, context:com.XXXX.ChatActivity@d5425a5
       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7071)
       at androidx.recyclerview.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:7194)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:10076)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4717)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4367)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
       at android.view.View.layout(View.java:20956)
       at android.view.ViewGroup.layout(ViewGroup.java:6396)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:20956)
       at android.view.ViewGroup.layout(ViewGroup.java:6396)
       at com.effective.android.panel.view.content.ContentContainerImpl.layoutContainer(ContentContainerImpl.kt:380)

**Comment by 15359947959** [comment]
收到了，辛苦啦

**Comment by HeroZ-Dodge** [comment]
这个异常，看上去像是由于业务逻辑引起的~

**Comment by HeroZ-Dodge** [comment]
你可以尝试从你们定义的 CatchLinearLayoutManager 入手试试

**Comment by YummyLau** [comment]
> > 这个异常，看上去像是由于业务逻辑引起的~
> 
> 你不是作者啊。。。。给我干蒙圈了。。。。不要瞎回复啊。。。。

@HeroZ-Dodge 是官方的

**Comment by YummyLau** [comment]
> `internal fun bindWindow(window: Window, windowInsetsRootView: View?) { this.window = window this.windowInsetsRootView = windowInsetsRootView keyboardAnimation = enableKeyboardAnimator && supportKeyboardAnimation() if (keyboardAnimation) { // 通过监听键盘动画，修改translationY线上面板 keyboardChangedAnimation() } else { // 通过获取键盘高度，触发onLayout修改面板高度 deviceRuntime = DeviceRuntime(context, window) window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN or WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE) deviceRuntime?.let { contentContainer.getInputActionImpl().updateFullScreenParams(it.isFullScreen, panelId, getCompatPanelHeight(panelId)) if (supportKeyboardFeature()) { keyboardChangedListener30Impl() } else { keyboardChangedListener(window, it) } hasAttachLister = true } } }` 源码这里， // 通过获取键盘高度，触发onLayout修改面板高度 这里的兼容是有问题的。Android10 以下，这个高度的获取等，都可能导致onLayout触发到RecycleView的刷新，以及回收。这里应该再处理下兜底策略 @15359947959
> 
> >

我们测试下，感谢反馈。
